import { ArrowUpRight, LockKeyhole } from 'lucide-react'
import { tools } from '@/data/tools'

const accents = { git: 'var(--accent)', docker: 'var(--accent)', linux: 'var(--accent)' }
export function ToolsGrid() {
  return <section id="tools" className="border-b border-border py-20 lg:py-28"><div className="mx-auto max-w-6xl px-5 lg:px-8">
    <div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 font-mono text-[10px] font-semibold uppercase tracking-[.16em] text-[var(--text-secondary)]">01 / choose your lab</p><h2 className="text-3xl font-semibold uppercase leading-[.95] tracking-[-.045em] sm:text-5xl">Tools for the work<br />you want to do.</h2></div><p className="max-w-xs text-sm leading-6 text-[var(--text-secondary)]">Start with the workflow that feels familiar. The fastest way to learn is to make a small thing move.</p></div>
    <div className="grid gap-6 md:grid-cols-3">{tools.map((tool, index) => { const Icon = tool.icon; const live = tool.status === 'live'; const accent = accents[tool.accent as keyof typeof accents]; const style = { '--focus-accent': accent, '--tool-accent': accent } as React.CSSProperties; const content = <><div className="flex items-center justify-between border-b border-[var(--border-dark)] px-5 py-4"><span className="font-mono text-3xl font-semibold tabular-nums">{String(index + 1).padStart(2, '0')}</span><span className={`inline-flex items-center gap-1.5 font-mono text-[9px] font-semibold uppercase tracking-wider ${live ? 'text-[var(--success)]' : 'text-[var(--muted-light)]'}`}>{live ? <span className="size-1.5 rounded-full bg-current" /> : <LockKeyhole className="size-2.5" />}{tool.status}</span><Icon className="size-5" /></div><div className="flex min-h-80 flex-col p-5"><div><h3 className="text-xl font-semibold uppercase tracking-[-.02em]">{tool.name}</h3><p className="mt-3 text-sm leading-6 text-[var(--text-secondary)]">{tool.description}</p></div><div className="dark-panel mt-auto overflow-x-auto border border-[var(--border-dark)] px-4 py-4 font-mono text-[11px] text-[#f1efe8]"><span className="text-[var(--accent)]">$ </span><span className="whitespace-nowrap">{tool.command}</span>{live && <ArrowUpRight className="ml-2 inline size-3.5 text-[var(--accent)] transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" />}</div></div></>; return live ? <a key={tool.name} href={tool.href} target="_blank" rel="noreferrer" aria-label={`Open ${tool.name} hands-on labs`} style={style} className="group border border-[var(--border-dark)] bg-[var(--surface)] shadow-[5px_5px_0_var(--ink)] transition-all duration-200 hover:-translate-y-1 hover:border-[var(--accent)] hover:shadow-[7px_7px_0_var(--ink)]">{content}</a> : <div key={tool.name} aria-disabled="true" style={style} className="border border-[var(--border-dark)] bg-[var(--surface)] opacity-75 shadow-[5px_5px_0_var(--ink)]">{content}</div> })}</div>
  </div></section>
}
