'use client'
import { motion, useReducedMotion } from 'framer-motion'
import { ArrowUpRight, LockKeyhole } from 'lucide-react'
import { tools } from '@/data/tools'

export function ToolsGrid() {
  const reduceMotion = useReducedMotion()
  return <motion.section initial={reduceMotion ? false : { opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.12 }} transition={{ duration: 0.55 }} id="tools" className="border-b border-border bg-white/45 py-24 dark:bg-white/[0.02] lg:py-32"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.16em] text-primary">01 / choose your surface</p><h2 className="text-3xl font-semibold tracking-[-0.04em] text-foreground sm:text-4xl">Tools for the work<br />you want to do.</h2></div><p className="max-w-xs text-sm leading-6 text-muted-foreground">Start with the workflow that feels familiar. The fastest way to learn is to make a small thing move.</p></div><div className="grid gap-5 md:grid-cols-3">{tools.map((tool) => { const Icon = tool.icon; const live = tool.status === 'live'; const content = <><div className="flex items-start justify-between"><span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider ${live ? 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-400/20 dark:bg-emerald-400/10 dark:text-emerald-300' : 'border-slate-200 bg-slate-50 text-slate-600 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300'}`}>{live ? <span className="size-1.5 rounded-full bg-[#10b981]" /> : <LockKeyhole className="size-3" />}{tool.status}</span><div className="flex size-11 items-center justify-center rounded-xl bg-indigo-50 text-indigo-700 dark:bg-indigo-400/10 dark:text-indigo-300"><Icon className="size-5" aria-hidden="true" /></div></div><div className="mt-auto"><h3 className="mt-12 text-xl font-semibold tracking-tight text-foreground">{tool.name}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{tool.description}</p><div className="mt-6 flex items-center justify-between rounded-lg border border-border bg-muted/60 px-3 py-2.5"><code className="max-w-[90%] truncate font-mono text-[11px]"><span className="mr-2 text-primary">$</span><span className="text-muted-foreground">{tool.command}</span></code>{live && <ArrowUpRight className="size-4 shrink-0 text-primary transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />}</div></div></>; return live ? <a key={tool.name} href={tool.href} target="_blank" rel="noreferrer" aria-label={`Open ${tool.name} hands-on labs`} className="group flex min-h-80 flex-col rounded-2xl border border-border bg-card p-6 shadow-sm transition-all hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl">{content}</a> : <div key={tool.name} aria-disabled="true" className="flex min-h-80 cursor-not-allowed flex-col rounded-2xl border border-border bg-card p-6 opacity-70 shadow-sm">{content}</div> })}</div></div></motion.section>
}
